### ISSUE TITLE
when there are spaces in the column names, the insert fails because the variable cannot have spaces in between them.

### ISSUE THREAD

**Issue by WinstonKyu** [m32/sqlalchemy-tds#7]
Here is an example to the problem on stackoverflow.
https://stackoverflow.com/questions/71428691/insert-into-cloud-sql-sql-server-column-names-with-spaces-in-them

**Comment by gordthompson** [comment]
Here is repro code that doesn't rely on pandas:

```python
import sqlalchemy as sa

connection_url = "mssql+pytds://scott:tiger^5HHH@192.168.0.199/test"
engine = sa.create_engine(
    connection_url,
    echo=True,
)

table_name = "issue_7"

with engine.begin() as conn:
    conn.exec_driver_sql(f"DROP TABLE IF EXISTS {table_name}")
    conn.exec_driver_sql(f"CREATE TABLE {table_name} (id int primary key, [my column] int)")

tbl = sa.Table(table_name, sa.MetaData(), autoload_with=engine)
with engine.begin() as conn:
    conn.execute(tbl.insert(), {"id": 1, "my column": 123})
"""
sqlalchemy.exc.OperationalError: (pytds.tds_base.OperationalError) Incorrect syntax near the keyword 'column'. Must declare the scalar variable "@my".
[SQL: INSERT INTO issue_7 (id, [my column]) VALUES (%(id)s, %(my column)s)]
[parameters: {'id': 1, 'my column': 123}]
"""
```

The same code works without error using `mssql+pyodbc://`.

Interestingly, the same code also works fine with `mssql+pymssql://` even though the SQL rendered by SQLAlchemy is the same:

```
INSERT INTO issue_7 (id, [my column]) VALUES (%(id)s, %(my column)s)
[generated in 0.00076s] {'id': 1, 'my column': 123}
```

apparently because pymssql (FreeTDS) performs the parameter substitution itself, so the SQL Server receives

```sql
INSERT INTO issue_7 (id, [my column]) VALUES (1, 123)
```

whereas pytds sends the parameters separately, so SQL Profiler shows

```sql
exec sp_executesql N'INSERT INTO issue_7 (id, [my column]) VALUES (@id, @my column)',N'@id INT,@my column INT',@id=1,@my column=123
```

**Comment by m32** [comment]
This is not a problem with this driver, but with the parameter handling in python-pytds.
<pre>
#!/usr/bin/env python3

# simplified code from pytds/__init__.py - around line 677
def _execute(operation, params):
            named_params = {}
            if isinstance(params, (list, tuple)):
                names = []
                pid = 1
                for val in params:
                    if val is None:
                        names.append('NULL')
                    else:
                        name = '@P{0}'.format(pid)
                        names.append(name)
                        named_params[name] = val
                        pid += 1
                if len(names) == 1:
                    operation = operation % names[0]
                else:
                    operation = operation % tuple(names)
            elif isinstance(params, dict):
                # prepend names with @
                rename = {}
                for name, value in params.items():
                    if value is None:
                        rename[name] = 'NULL'
                    else:
                        mssql_name = '@{0}'.format(name)
                        rename[name] = mssql_name
                        named_params[mssql_name] = value
                operation = operation % rename

            print('operation', operation)
            print('params', params)
            print('named_params', named_params)

def main():
    params = {"id": 1, "my column": 123}
    operation = 'INSERT INTO issue_7 (id, [my column]) VALUES (%(id)s, %(my column)s)]'
    _execute(operation, params)
main()
</pre>

**Comment by m32** [comment]
Issue created in pytds: https://github.com/denisenkom/pytds/pull/130
